'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),EDGE='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';
const source=name=>fs.readFileSync(path.join(ROOT,'web',name),'utf8');

(async()=>{
 const browser=await chromium.launch({executablePath:EDGE,headless:true,args:['--disable-gpu']});
 try{
  const page=await browser.newPage({viewport:{width:360,height:640},deviceScaleFactor:3,locale:'ru-RU'}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
  const screenshotDir=path.join(ROOT,'dist','RuStore','screenshots','phone');fs.mkdirSync(screenshotDir,{recursive:true});
  let html=source('index.html').replace('<link rel="stylesheet" href="style.css">',`<style>${source('style.css')}</style>`).replace(/<script src="[^"]+"><\/script>/g,'').replace(/<meta http-equiv="Content-Security-Policy"[^>]+>/g,'');
  await page.route('https://appassets.androidplatform.net/',route=>route.fulfill({status:200,contentType:'text/html',body:html}));await page.goto('https://appassets.androidplatform.net/');await page.addScriptTag({content:`window.__hostStored='';window.__savedFile=null;window.AndroidFiles={loadHostState:()=>window.__hostStored,saveHostState:value=>(window.__hostStored=value,true),hostStateSize:()=>new TextEncoder().encode(window.__hostStored).length,startHostServer:()=>JSON.stringify(['http://192.168.1.20:8787']),stopHostServer:()=>{},hostRespond:()=>{},saveText:(name,text,mime)=>{window.__savedFile={name,text,mime}},updateWidget:()=>{},requestReview:()=>{},openExternal:()=>false};`});
  for(const name of ['domain.js','host.js','transfer.js','vendor/qr-encode.js','vendor/qr-decode.js','vendor/code128-patterns.js','codes.js','reports.js','scanner.js'])await page.addScriptTag({content:source(name)});
  let app=source('app.js').trimEnd();assert.ok(app.endsWith('init();'));app=app.slice(0,-7)+`const mem=new Map();openDB=async()=>({});getKV=async k=>mem.has(k)?D.copy(mem.get(k)):undefined;putKV=async(k,v)=>{mem.set(k,D.copy(v));};delKV=async k=>mem.delete(k);applyLocal=async c=>{const result=D.execute(await getKV(activeKey())||state,c);await putKV(activeKey(),result);return result;};mutateQueue=async edit=>{queue=edit(await getKV(queueKey())||[]);await putKV(queueKey(),queue);return queue;};saveCfg=()=>{};inferServer=()=>'';init();`;
  await page.addScriptTag({content:app});await page.getByRole('button',{name:/Сделать телефон или планшет главным/}).click();
  await page.locator('[name="space"]').fill('Мобильный склад');await page.locator('[name="device"]').fill('Планшет в мастерской');await page.locator('[name="name"]').fill('Виктор');await page.locator('[name="login"]').fill('owner');await page.locator('[name="password"]').fill('very-secure-password');await page.locator('#host-create-form input[type=checkbox]').check();await page.locator('button[form="host-create-form"]').click();
  await page.waitForSelector('#main');assert.equal(await page.evaluate(()=>cfg.mode),'host');assert.match(await page.locator('.sync-btn').innerText(),/Главное/);
  await page.locator('.mobile-nav [data-nav="settings"]').click();assert.match(await page.locator('.settings-card').first().innerText(),/доступно|Главное устройство/i);await page.screenshot({path:path.join(screenshotDir,'06-main-device-1080x1920.png'),animations:'disabled'});await page.getByRole('button',{name:/Участники и приглашения/}).click();assert.equal(await page.locator('#invite-address').inputValue(),'http://192.168.1.20:8787');assert.match(await page.locator('#invite-address option').innerText(),/рекомендуется/);await page.screenshot({path:path.join(screenshotDir,'07-roles-1080x1920.png'),animations:'disabled'});await page.getByRole('button',{name:'Закрыть'}).click();
  await page.getByRole('button',{name:/Передать главный склад/}).click();await page.locator('[name="device"]').fill('Новый компьютер');await page.locator('#host-transfer-form input[type=checkbox]').check();await page.locator('button[form="host-transfer-form"]').click();await page.getByText('Защищённый перенос готов').waitFor();await page.locator('#save-transfer').click();const saved=await page.evaluate(()=>window.__savedFile);assert.match(saved.name,/\.yarus$/);assert.equal(saved.mime,'application/vnd.yarus+json');assert.equal(saved.text.includes('very-secure-password'),false);assert.equal(await page.evaluate(()=>YarusAndroidHost.info().host.status),'retired');assert.deepEqual(errors,[]);
  console.log('PASS: mobile main-device creation, team address and encrypted handoff UI');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
