/* ЯРУС — codes are identifiers, never executable commands or permissions. */
(function(root){'use strict';
const safeID=s=>typeof s==='string'&&/^[A-Za-z0-9_-]{8,80}$/.test(s)&&!['__proto__','constructor','prototype'].includes(s);
function clean(value){const s=String(value??'').trim();if(!s||s.length>512||/[\x00-\x1f\x7f]/.test(s))throw new Error('Код пустой, слишком длинный или содержит служебные символы.');return s;}
function internal(spaceId,kind,id){if(!safeID(spaceId)||!safeID(id)||!['item','place'].includes(kind))throw new Error('Сначала сохраните карточку и обновите общий сервер.');return `YARUS:1:${spaceId}:${kind}:${id}`;}
function parse(value){const s=clean(value);if(/^YARUS:/i.test(s)){const p=s.split(':');if(p.length!==5||p[0]!=='YARUS'||p[1]!=='1'||!safeID(p[2])||!['item','place'].includes(p[3])||!safeID(p[4]))throw new Error('Этот код ЯРУС повреждён или относится к другой версии.');return {kind:p[3],spaceId:p[2],id:p[4],raw:s};}if(s.length>80)throw new Error('Внешний код длиннее 80 символов. Эта версия не ведёт поштучную маркировку.');return {kind:'external',raw:s};}
function resolve(s,value){const p=parse(value);if(p.kind!=='external'){if(!s.space.id||p.spaceId!==s.space.id)throw new Error('QR-код относится к другому складу. Подключитесь к тому же общему складу или восстановите его копию.');const entity=(p.kind==='item'?s.items:s.places)[p.id];if(!entity)throw new Error('Карточка из QR-кода не найдена в этом складе. Проверьте синхронизацию.');return {...p,entity};}const hits=Object.values(s.items).filter(x=>x.barcode&&x.barcode.toLowerCase()===p.raw.toLowerCase());if(hits.length>1)throw new Error('Найдено несколько карточек с одинаковым кодом. Исправьте дубликаты.');return hits.length?{...p,kind:'item',id:hits[0].id,entity:hits[0]}:p;}
function matrix(payload){const s=clean(payload);if(!/^[\x20-\x7e]+$/.test(s))throw new Error('Для этикетки нужен внутренний код ЯРУС.');const qr=new root.YarusQREncoder(-1,0);qr.addData(s);qr.make();return qr.modules;}
function svg(payload){const a=matrix(payload),n=a.length+8;let d='';a.forEach((row,y)=>row.forEach((v,x)=>{if(v)d+=`M${x+4},${y+4}h1v1h-1z`;}));return `<svg xmlns="http://www.w3.org/2000/svg" width="360" height="360" viewBox="0 0 ${n} ${n}" shape-rendering="crispEdges"><rect width="${n}" height="${n}" fill="white"/><path d="${d}" fill="black"/></svg>`;}
function eanCheck(s){if(!/^\d{8}$|^\d{13}$/.test(s))return false;let sum=0;for(let i=s.length-2,j=0;i>=0;i--,j++)sum+=Number(s[i])*(j%2?1:3);return (10-sum%10)%10===+s[s.length-1];}
const L=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'];
const G=['0100111','0110011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'];
const R=L.map(s=>[...s].map(c=>c==='0'?'1':'0').join(''));
const parity=['LLLLLL','LLGLGG','LLGGLG','LLGGGL','LGLLGG','LGGLLG','LGGGLL','LGLGLG','LGLGGL','LGGLGL'];
function eanBits(bits){for(const count of [13,8]){const n=count===13?95:67;if(bits.length!==n||bits.slice(0,3)!=='101'||bits.slice(-3)!=='101')continue;const side=count===13?6:4;if(bits.slice(3+side*7,8+side*7)!=='01010')continue;let str='',pat='',ok=true;for(let j=0;j<side;j++){const b=bits.slice(3+j*7,10+j*7);let k=L.indexOf(b);if(k>=0)pat+='L';else{k=G.indexOf(b);pat+='G';}if(k<0)ok=false;str+=k;}for(let j=0;j<side;j++){const k=R.indexOf(bits.slice(8+side*7+j*7,15+side*7+j*7));if(k<0)ok=false;str+=k;}if(count===13){const first=parity.indexOf(pat);if(first<0)ok=false;str=first+str;}else if(pat!=='LLLL')ok=false;if(ok&&eanCheck(str))return {text:str,format:count===13?'EAN-13':'EAN-8'};}return null;}
function matchWidths(run,pat){const sum=run.reduce((a,b)=>a+b,0),total=[...pat].reduce((a,b)=>a+Number(b),0),scale=sum/total;if(scale<.65)return Infinity;let e=0;for(let i=0;i<run.length;i++){const d=Math.abs(run[i]/scale-Number(pat[i]));if(d>.85)return Infinity;e+=d*d;}return e/run.length;}
function decode128(runs,start){const pats=root.YarusCode128Patterns;let startCode=-1,best=.18;for(let k=103;k<=105;k++){const score=matchWidths(runs.slice(start,start+6),pats[k]);if(score<best){best=score;startCode=k;}}if(startCode<0)return null;const seq=[startCode];let i=start+6;
 for(let limit=0;limit<83&&i+6<runs.length;limit++,i+=6){if(seq.length>2&&matchWidths(runs.slice(i,i+7),pats[106])<.18){let checksum=seq[0];for(let j=1;j<seq.length-1;j++)checksum+=j*seq[j];if(checksum%103!==seq[seq.length-1])return null;let set=startCode===105?'C':startCode===104?'B':'A',out='';for(let j=1;j<seq.length-1;j++){const c=seq[j];if(c===102)return null;/* FNC1 / GS1 deliberately not interpreted as a commodity card. */if(set==='C'){if(c===100){set='B';continue;}if(c===101){set='A';continue;}if(c>99)return null;out+=String(c).padStart(2,'0');}else if(c===99)set='C';else if(c===100&&set==='A')set='B';else if(c===101&&set==='B')set='A';else if(c===98||c>=96)return null;else out+=String.fromCharCode(set==='B'||c<64?c+32:c-64);}if(!out||/[\x00-\x1f]/.test(out))return null;return {text:out,format:'Code 128'};}
 let chosen=-1,err=.18;for(let k=0;k<=102;k++){const score=matchWidths(runs.slice(i,i+6),pats[k]);if(score<err){err=score;chosen=k;}}if(chosen<0)return null;seq.push(chosen);}return null;}
function lineDecode(gray){let lo=255,hi=0;for(const v of gray){lo=Math.min(lo,v);hi=Math.max(hi,v);}if(hi-lo<65)return null;const threshold=(lo+hi)/2;let runs=[],colors=[],count=1,last=gray[0]<threshold;for(let i=1;i<gray.length;i++){const bit=gray[i]<threshold;if(bit===last)count++;else{runs.push(count);colors.push(last);last=bit;count=1;}}runs.push(count);colors.push(last);
 for(let i=1;i<runs.length-30;i++){if(!colors[i])continue;const gs=(runs[i]+runs[i+1]+runs[i+2])/3;if(gs<.7||runs[i-1]<5*gs)continue;const c=decode128(runs,i);if(c)return c;
 for(const k of [59,43]){if(i+k>runs.length)continue;const part=runs.slice(i,i+k),modules=k===59?95:67,scale=part.reduce((a,b)=>a+b,0)/modules;if(scale<.7||Math.abs(gs/scale-1)>.3)continue;let bits='',ok=true;for(let j=0;j<part.length;j++){const n=Math.round(part[j]/scale);if(n<1||n>4||Math.abs(n-part[j]/scale)>.65){ok=false;break;}bits+=(j%2?'0':'1').repeat(n);}if(ok){const r=eanBits(bits);if(r)return r;}}
 }return null;}
function decode1D(image){const {data,width:w,height:h}=image;const results=new Map();for(const vertical of [false,true]){const len=vertical?h:w,other=vertical?w:h;for(const fraction of [.5,.4,.6,.3,.7]){const index=Math.floor(other*fraction),gray=new Uint8Array(len);for(let i=0;i<len;i++){const k=4*(vertical?i*w+index:index*w+i);gray[i]=(77*data[k]+150*data[k+1]+29*data[k+2])>>8;}for(const row of [gray,Uint8Array.from(gray).reverse()]){const r=lineDecode(row);if(r){const key=r.format+':'+r.text,count=(results.get(key)||0)+1;results.set(key,count);if(count>=2)return r;}}}}return null;}
function decode(image){const qr=root.YarusQRDecode(image.data,image.width,image.height);if(qr?.data)return {text:qr.data,format:'QR'};return decode1D(image);}
root.YarusCodes={clean,internal,parse,resolve,matrix,svg,eanCheck,decode,decode1D,lineDecode,eanBits};
})(globalThis);
