/* ЯРУС 1.0 — shared camera, keyboard-scanner and label workflow. */
let yarusScanSession=null;
function closeScanner(){const s=yarusScanSession;if(!s)return;s.closed=true;clearTimeout(s.timer);s.stream?.getTracks().forEach(t=>t.stop());s.root.remove();document.removeEventListener('keydown',s.keys,true);yarusScanSession=null;document.body.style.overflow=s.previousOverflow;s.focus?.focus?.({preventScroll:true});}
function readScanImage(file){return new Promise((resolve,reject)=>{const fail=()=>reject(new Error('Не удалось открыть изображение. Выберите файл JPG, PNG или WEBP и повторите.')),reader=new FileReader();reader.onerror=fail;reader.onabort=fail;reader.onload=()=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=fail;image.src=String(reader.result||'');};try{reader.readAsDataURL(file);}catch{fail();}});}
function openScanner(target='lookup',autoStart=false){
 closeScanner();const root=document.createElement('div');root.id='scan-root';root.className='scan-backdrop';const oldFocus=document.activeElement;
 root.innerHTML=`<section class="scan-panel" role="dialog" aria-modal="true" aria-labelledby="scan-title"><header class="scan-header"><div><h2 id="scan-title">Сканировать код</h2><p>${target==='invite'?'Считайте одноразовое приглашение с экрана компьютера.':target==='barcode'?'Код будет вписан в карточку, но не сохранён автоматически.':target==='item'?'Выберите товар для текущего движения.':target==='place'||target==='destination'?'Отсканируйте QR нужного места хранения.':'Найдите товар или место хранения.'}</p></div><button class="btn iconbtn quiet" id="scan-close" aria-label="Закрыть сканер">${ic('close')}</button></header><div class="scan-body"><div class="scan-viewport"><video id="scan-video" playsinline muted></video><div id="scan-cover">${ic('barcode')}<p>Наведите на QR или штрихкод.<br>Код должен быть целиком в кадре.</p></div></div><p id="scan-status" role="status" aria-live="polite">Камера включается только по вашей кнопке. Фото и видео никуда не отправляются.</p><div class="row wrap"><button class="btn primary" id="scan-start">${ic('device')}Включить камеру</button><button class="btn" id="scan-torch" hidden>Фонарик</button><label class="btn" for="scan-image">${ic('file')}Из изображения</label><input type="file" id="scan-image" accept="image/*" class="visually-hidden"></div><select id="scan-cameras" aria-label="Выбор камеры" hidden></select><form id="scan-manual-form" class="scan-manual"><label class="field">Ввести код или считать USB / Bluetooth-сканером<input id="scan-manual" class="input" autocomplete="off" autocapitalize="none" spellcheck="false" maxlength="512" placeholder="Код → Enter" aria-label="Код вручную"></label><button class="btn" type="submit">Найти</button></form><div id="scan-result" aria-live="polite"></div><details class="small"><summary>Какие коды поддерживаются</summary><p>Встроенное распознавание: QR-приглашения ЯРУС, QR товаров и мест, EAN-13, EAN-8, Code 128 без GS1. Держите код ровно и достаточно близко. GS1, Data Matrix и поштучная маркировка не входят в эту версию. Обычные ссылки из QR не открываются. Сканирование не проводит приход или расход.</p></details></div></section>`;
 document.body.append(root);const s={root,target,closed:false,stream:null,timer:null,focus:oldFocus,previousOverflow:document.body.style.overflow,generation:0};yarusScanSession=s;document.body.style.overflow='hidden';const el=id=>root.querySelector('#'+id),status=(text,error=false)=>{el('scan-status').textContent=text;el('scan-status').className=error?'error-text':'';};
 s.keys=e=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeScanner();}else if(e.key==='Tab'){const list=[...root.querySelectorAll('button,input,select,summary')].filter(x=>!x.disabled&&!x.hidden&&x.getClientRects().length),first=list[0],last=list[list.length-1];if(e.shiftKey&&(document.activeElement===first||!root.contains(document.activeElement))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||!root.contains(document.activeElement))){e.preventDefault();first?.focus();}e.stopImmediatePropagation();}};document.addEventListener('keydown',s.keys,true);el('scan-close').onclick=closeScanner;if(autoStart)el('scan-start').focus();else el('scan-manual').focus();
 function stopVideo(){s.generation++;s.stream?.getTracks().forEach(t=>t.stop());s.stream=null;clearTimeout(s.timer);el('scan-torch').hidden=true;el('scan-start').disabled=false;el('scan-start').textContent='Включить камеру';}
 function accept(value,format=''){if(s.closed)return;stopVideo();try{if(target==='invite'){const invite=YarusCodes.parseInvite(value);if(invite.expires*1000<Date.now())throw new Error('Срок действия приглашения истёк. Создайте новое на компьютере.');closeScanner();accountModal('join',{server:invite.server,code:invite.code,transportKey:invite.transportKey});toast('Приглашение считано. Придумайте логин и пароль.');return;}const result=YarusCodes.resolve(state,value);if(target==='barcode'){if(result.spaceId)throw new Error('Это внутренний QR ЯРУС. Для поля «Штрихкод» используйте заводской код; QR этой карточки создаётся отдельно.');const f=$('#item-form');if(!f)throw new Error('Карточка закрыта. Откройте её заново.');if(result.kind==='item'&&result.id!==f.dataset.id)throw new Error('Этот код уже привязан к товару «'+result.entity.name+'».');f.elements.barcode.value=result.raw;modalDirty=true;closeScanner();return;}
 if(target==='place'||target==='destination'){if(result.kind!=='place')throw new Error('Нужен QR места хранения, а не товара.');const select=$(target==='destination'?'#op-destination':'#op-place');if(!select)throw new Error('Форма движения закрыта.');select.value=result.id;select.dispatchEvent(new Event('change',{bubbles:true}));modalDirty=true;closeScanner();return;}
 if(target==='item'){if(result.kind!=='item')throw new Error('Код товара не найден. Сначала добавьте или привяжите его в разделе «Товары».');if(result.entity.archived)throw new Error('Товар в архиве. Верните карточку из архива перед движением.');$('#op-item').value=result.id;$('#op-item').dispatchEvent(new Event('change',{bubbles:true}));modalDirty=true;closeScanner();return;}
 if(result.kind==='item'){closeScanner();detailModal(result.id);return;}if(result.kind==='place'){closeScanner();closeModal(true);page='stock';placeFilter=result.id;search='';category='';stockFilter='all';render();toast('Место: '+result.entity.name);return;}
 status('Код прочитан'+(format?' · '+format:'')+'. В этом складе он пока не привязан.');el('scan-result').innerHTML=`<div class="notice"><strong>Новый код</strong><p class="scan-code">${esc(result.raw)}</p>${canWrite()?'<div class="row wrap"><button class="btn primary" id="scan-create">Создать товар</button><button class="btn" id="scan-bind">Привязать к существующему</button></div>':'Создавать и изменять карточки может сотрудник или владелец.'}</div>`;
 if(canWrite()){el('scan-create').onclick=()=>{const value=result.raw;closeScanner();newItemModal();$('#item-form').elements.barcode.value=value;modalDirty=true;};el('scan-bind').onclick=()=>{const value=result.raw;closeScanner();bindCodeModal(value);};}
 }catch(e){status(e.message,true);}}
 async function start(deviceId=''){
 stopVideo();const generation=s.generation;status('Запрашиваем доступ к камере…');el('scan-start').disabled=true;
 try{if(document.hidden)throw new Error('Вернитесь в ЯРУС, чтобы включить камеру.');if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error('Камера недоступна по этому адресу. Откройте установленное приложение либо HTTPS. В локальной сети используйте APK, изображение или внешний сканер.');
 const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:deviceId?{deviceId:{exact:deviceId},width:{ideal:1280},height:{ideal:720}}:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});if(s.closed||s.generation!==generation){stream.getTracks().forEach(t=>t.stop());return;}s.stream=stream;const video=el('scan-video');video.srcObject=stream;await video.play();if(s.closed||s.generation!==generation)return;el('scan-cover').hidden=true;status('Наведите на один код. После распознавания камера выключится.');el('scan-start').disabled=false;el('scan-start').textContent='Остановить камеру';
 try{const devices=(await navigator.mediaDevices.enumerateDevices()).filter(x=>x.kind==='videoinput');if(!s.closed){el('scan-cameras').innerHTML=devices.map((d,i)=>`<option value="${esc(d.deviceId)}">${esc(d.label||'Камера '+(i+1))}</option>`).join('');el('scan-cameras').value=stream.getVideoTracks()[0].getSettings().deviceId||'';el('scan-cameras').hidden=devices.length<2;}}catch{}
 const track=stream.getVideoTracks()[0];try{if(track.getCapabilities?.().torch){el('scan-torch').hidden=false;el('scan-torch').onclick=async()=>{try{s.torch=!s.torch;await track.applyConstraints({advanced:[{torch:s.torch}]});el('scan-torch').textContent=s.torch?'Выключить фонарик':'Фонарик';}catch{status('Фонарик недоступен на этой камере.');}};}}catch{}
 let detector=null;try{if(window.BarcodeDetector){const formats=await BarcodeDetector.getSupportedFormats();const allowed=formats.filter(f=>['qr_code','ean_13','ean_8','code_128'].includes(f));if(allowed.length)detector=new BarcodeDetector({formats:allowed});}}catch{}
 const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let last='',repeats=0;
 async function tick(){if(s.closed||!s.stream||generation!==s.generation)return;try{let result=null;if(detector){try{const list=await detector.detect(video);if(list.length===1)result={text:list[0].rawValue,format:list[0].format};}catch{detector=null;}}
 if(!result&&video.videoWidth){const factor=Math.min(1,768/video.videoWidth);canvas.width=Math.max(40,Math.floor(video.videoWidth*factor/8)*8);canvas.height=Math.max(40,Math.floor(video.videoHeight*factor/8)*8);ctx.drawImage(video,0,0,canvas.width,canvas.height);result=YarusCodes.decode(ctx.getImageData(0,0,canvas.width,canvas.height));}
 if(result){if(result.text===last)repeats++;else{last=result.text;repeats=1;}if(repeats>=2){accept(result.text,result.format);return;}}else{repeats=0;last='';}
 }catch{/* No code in this frame; keep scanning, not a stock transaction. */}if(!s.closed&&s.stream&&generation===s.generation)s.timer=setTimeout(tick,220);}tick();
 }catch(e){if(s.closed)return;stopVideo();status(e.name==='NotAllowedError'?'Доступ к камере не разрешён. Разрешите камеру для ЯРУС в настройках телефона или используйте изображение / ручной ввод.':e.name==='NotFoundError'?'Камера не найдена. Подключите веб-камеру, выберите изображение или используйте внешний сканер.':e.name==='NotReadableError'?'Камера занята другим приложением. Закройте его и повторите.':e.message||'Не удалось включить камеру.',true);}
 }
 el('scan-start').onclick=()=>s.stream?(stopVideo(),status('Камера выключена.')):start();el('scan-cameras').onchange=()=>start(el('scan-cameras').value);
 el('scan-manual-form').onsubmit=e=>{e.preventDefault();accept(el('scan-manual').value);};
 el('scan-image').onchange=async()=>{stopVideo();const file=el('scan-image').files[0];if(!file)return;try{if(file.size>15e6)throw new Error('Выберите изображение до 15 МБ.');const image=await readScanImage(file);if(s.closed)return;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),factor=Math.min(1,1600/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.max(40,Math.floor(image.naturalWidth*factor/8)*8);canvas.height=Math.max(40,Math.floor(image.naturalHeight*factor/8)*8);ctx.drawImage(image,0,0,canvas.width,canvas.height);const result=YarusCodes.decode(ctx.getImageData(0,0,canvas.width,canvas.height));if(!result)throw new Error('Не удалось прочитать код. Выберите чёткое изображение одного кода целиком, без наклона и бликов.');accept(result.text,result.format);}catch(e){if(!s.closed)status(e.message||'Не удалось обработать изображение.',true);}};
 if(autoStart)start();
}
function bindCodeModal(code){if(!canWrite())return;modal('Привязать код к товару','После подтверждения код будет записан в карточку.',`<form id="bind-code-form" class="stack"><div class="notice scan-code">${esc(code)}</div><label class="field">Найдите товар<input class="input" id="bind-search" placeholder="Название или артикул"></label><label class="field">Товар<select name="item" id="bind-item">${itemOptions('')}</select></label><p id="bind-hint" class="notice"></p><div class="notice warn">Остаток и история не изменятся. Уже существующий код будет заменён только после отдельного подтверждения.</div></form>`,formButtons('bind-code-form','Привязать код'));
 const select=$('#bind-item');function hint(){const x=state.items[select.value];$('#bind-hint').textContent=x?(x.barcode?'Текущий код: '+x.barcode:'Заводской код ещё не указан.'):'Нет подходящих товаров.';}$('#bind-search').oninput=e=>{const term=e.target.value.toLowerCase();select.innerHTML=activeItems().filter(x=>(x.name+' '+x.sku).toLowerCase().includes(term)).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');hint();};select.onchange=hint;hint();$('#bind-code-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;runForm(f,async()=>{const x=state.items[select.value];if(!x)throw new Error('Выберите товар.');if(x.barcode&&x.barcode!==code&&!confirm('Заменить код '+x.barcode+' у товара «'+x.name+'»?'))throw new Error('Код не изменён.');const r=await send({id:id(),type:'item',item:{...x,barcode:code}});toast(r.saved?'Код привязан.':'Привязка ожидает подтверждения сервера.');});};}
function upgradeOperation(kind){const f=$('#operation-form');if(!f)return;f.noValidate=true;for(const [select,target,label] of [['#op-item','item','Сканировать товар'],['#op-place','place','Сканировать место'],['#op-destination','destination','Сканировать место назначения']]){const el=$(select);if(el){const b=document.createElement('button');b.type='button';b.className='linkbtn scan-field-btn';b.textContent=label;b.onclick=()=>openScanner(target);el.parentElement.append(b);}}
 const input=$('#op-qty'),error=document.createElement('span');error.id='quantity-error';error.className='quantity-error';error.setAttribute('role','status');input.setAttribute('aria-describedby','qty-unit quantity-error');input.parentElement.append(error);
 function validate(){let message='';const item=state.items[f.elements.itemId.value],p=f.elements.place.value;try{if(input.value.trim()){const qty=D.decimal(input.value),available=state.stocks[D.key(item.id,p)]?.qty||0;if(kind!=='count'&&!qty)message='Количество должно быть больше нуля.';else if(['out','transfer'].includes(kind)&&qty>available)message=`В месте «${placeName(p)}» доступно ${q(available)} ${item.unit}. Вы указали ${q(qty)} — не хватает ${q(qty-available)} ${item.unit}. Уменьшите количество или выберите другое место.`;else if(kind==='transfer'&&f.elements.destination.value===p)message='Выберите разные места: откуда и куда.';}}catch(e){message=e.message;}error.textContent=message;input.setAttribute('aria-invalid',message?'true':'false');return !message;}
 f.addEventListener('input',validate);f.addEventListener('change',validate);f.addEventListener('submit',e=>{if(!validate()){e.preventDefault();e.stopImmediatePropagation();error.scrollIntoView({block:'center',behavior:'smooth'});return;}if(!f.checkValidity()){e.preventDefault();e.stopImmediatePropagation();f.reportValidity();}},true);validate();}
function labelCanvas(payload,title,subtitle){const c=document.createElement('canvas');c.width=840;c.height=480;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const m=YarusCodes.matrix(payload),n=m.length+8,scale=Math.floor(360/n),offset=24;const top=Math.floor((c.height-n*scale)/2);x.fillStyle='#000';m.forEach((row,y)=>row.forEach((v,col)=>{if(v)x.fillRect(offset+(col+4)*scale,top+(y+4)*scale,scale,scale);}));const left=offset+n*scale+26,width=c.width-left-25;x.font='bold 36px sans-serif';x.fillText('ЯРУС',left,65);x.font='bold 40px sans-serif';const text=String(title);let lines=[],line='';for(const char of text){if(x.measureText(line+char).width>width){lines.push(line);line=char;}else line+=char;}if(line)lines.push(line);if(lines.length>4){lines=lines.slice(0,4);lines[3]=lines[3].slice(0,-2)+'…';}lines.forEach((l,i)=>x.fillText(l,left,118+i*46));x.font='28px sans-serif';const sub=String(subtitle);let s=sub;while(x.measureText(s).width>width&&s.length)s=s.slice(0,-1);if(s!==sub)s=s.slice(0,-1)+'…';x.fillText(s,left,365);x.font='22px sans-serif';x.fillText('Откройте сканером ЯРУС',left,418);return c;}
function labelsPDF(canvas,copies=1,a4=true){copies=Number(copies);if(!Number.isInteger(copies)||copies<1||copies>12)throw new Error('Выберите от 1 до 12 этикеток.');const jpeg=atob(canvas.toDataURL('image/jpeg',.98).split(',')[1]);let hex='';for(let i=0;i<jpeg.length;i++)hex+=jpeg.charCodeAt(i).toString(16).padStart(2,'0');hex+='>';const mm=72/25.4,w=a4?210*mm:70*mm,h=a4?297*mm:40*mm;let stream='';for(let i=0;i<(a4?copies:1);i++){const x=a4?(30+(i%2)*80)*mm:0,y=a4?h-(16+Math.floor(i/2)*45+40)*mm:0;stream+=`q ${70*mm} 0 0 ${40*mm} ${x} ${y} cm /Im0 Do Q\n`;}
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>',`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${w} ${h}] /Resources << /XObject << /Im0 5 0 R >> >> /Contents 4 0 R >>`,`<< /Length ${stream.length} >>\nstream\n${stream}endstream`,`<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter [/ASCIIHexDecode /DCTDecode] /Length ${hex.length} >>\nstream\n${hex}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF\n';return pdf;}
function labelModal(kind,entityID){try{const entity=(kind==='item'?state.items:state.places)[entityID];if(!entity)return;const payload=YarusCodes.internal(state.space.id,kind,entity.id);modal('QR-этикетка',kind==='item'?'Постоянный код товара. Остаток не записан в QR.':'Постоянный код места хранения.',`<div class="stack"><div class="label-preview" id="label-preview"></div><p class="notice">${esc(entity.name)}<br>Склад: ${esc(state.space.name)}. Код откроет карточку только в этом складе или его полной копии. Сам по себе код доступа не даёт.</p><div class="form-grid"><label class="field">Бумага<select id="label-paper"><option value="a4">Лист A4 · до 12 этикеток</option><option value="single">Одна этикетка · 70 × 40 мм</option></select></label><label class="field">Количество на A4<input class="input" id="label-copies" type="number" min="1" max="12" value="1"></label></div><button class="btn primary" id="label-pdf">${ic('download')}Сохранить PDF для печати</button><button class="btn" id="label-svg">Сохранить QR как SVG</button><p class="small muted">Печатайте PDF в масштабе 100% («Фактический размер»). Этикетка — 70 × 40 мм. Сначала проверьте одну наклейку камерой. Длинное название сокращается; полное — в карточке. Расположение на A4: две колонки, шесть рядов; не шаблон готовой самоклейки.</p><details><summary class="small">Текст кода для внешнего сканера</summary><p class="scan-code">${esc(payload)}</p></details></div>`);const canvas=labelCanvas(payload,entity.name,kind==='item'?(entity.sku||'Товар'):'Место хранения');$('#label-preview').append(canvas);$('#label-paper').onchange=()=>{$('#label-copies').disabled=$('#label-paper').value==='single';};$('#label-pdf').onclick=()=>{try{downloadText('YARUS-label-'+entity.id+'.pdf',labelsPDF(canvas,Number($('#label-copies').value),$('#label-paper').value==='a4'),'application/pdf');}catch(e){formError(e);}};$('#label-svg').onclick=()=>downloadText('YARUS-QR-'+entity.id+'.svg',YarusCodes.svg(payload),'image/svg+xml');}catch(e){toast(e.message,'error');}}
function pauseScanner(){const s=yarusScanSession;if(!s)return;s.generation++;s.stream?.getTracks().forEach(t=>t.stop());s.stream=null;clearTimeout(s.timer);const b=s.root.querySelector('#scan-start');b.disabled=false;b.textContent='Включить камеру';s.root.querySelector('#scan-status').textContent='Камера выключена. Нажмите кнопку, чтобы продолжить.';}
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseScanner();});
